'use client';

import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "../../lib/supabase/browser";
import {ExplorePage,ExploreHeader,EmptyState} from "../ExploreChrome";

const notificationSelect="*,matches(id,home_score,away_score,home_team:teams!matches_home_team_id_fkey(name),away_team:teams!matches_away_team_id_fkey(name))";

export default function NotificationsPage(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let channel;let mounted=true;const supabase=createSupabaseBrowserClient();(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href="/login";return;}const {data,error:fetchError}=await supabase.from("user_notifications").select(notificationSelect).order("created_at",{ascending:false}).limit(100);if(!mounted)return;if(fetchError)setError(fetchError.message);else setItems(data||[]);setLoading(false);channel=supabase.channel("zedek-notification-page-"+session.user.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"user_notifications",filter:"user_id=eq."+session.user.id},async payload=>{if(!mounted)return;const {data:freshNotification,error:refreshError}=await supabase.from("user_notifications").select(notificationSelect).eq("id",payload.new.id).maybeSingle();if(!mounted)return;if(refreshError||!freshNotification){setItems(current=>[payload.new,...current].slice(0,100));return;}setItems(current=>[freshNotification,...current.filter(item=>item.id!==freshNotification.id)].slice(0,100));}).subscribe();})();return()=>{mounted=false;if(channel)supabase.removeChannel(channel);};},[]);
 async function markAll(){const supabase=createSupabaseBrowserClient();const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {error}=await supabase.from("user_notifications").update({read_at:new Date().toISOString()}).eq("user_id",session.user.id).is("read_at",null);if(!error)setItems(current=>current.map(item=>({...item,read_at:item.read_at||new Date().toISOString()})));}
 async function mark(id){const supabase=createSupabaseBrowserClient(),now=new Date().toISOString();const {error}=await supabase.from("user_notifications").update({read_at:now}).eq("id",id);if(!error)setItems(current=>current.map(item=>item.id===id?{...item,read_at:now}:item));}
 return <ExplorePage><ExploreHeader title="Notifications" eyebrow="Your Football" description="Important updates from the teams and matches you follow."/><div className="hub-page-actions notification-actions"><a className="hub-filter active" href="/settings">Notification settings →</a><button className="hub-filter" onClick={markAll}>Mark all read</button></div>{error?<EmptyState>{error}</EmptyState>:loading?<EmptyState>Loading notifications…</EmptyState>:items.length?<section className="hub-notification-feed">{items.map(x=><button className={"hub-notification "+(x.read_at?"read":"")} key={x.id} onClick={()=>mark(x.id)}><span className="hub-notification-icon">{x.read_at?"✓":"!"}</span><span className="hub-notification-main"><b>{x.title}</b><small>{x.body}</small><time>{new Intl.DateTimeFormat("en-GH",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Accra"}).format(new Date(x.created_at))}</time></span>{!x.read_at?<i>NEW</i>:<i>READ</i>}</button>)}</section>:<EmptyState><strong>No notifications yet.</strong><span>Follow a team or match and this space will stay ready for important football updates.</span></EmptyState>}</ExplorePage>;
}