'use client';

import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {createSupabaseBrowserClient} from "../../../lib/supabase/browser";

function date(v){return v?new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v)):"Date TBC"}
function ageFromDob(v){if(!v)return null;const d=new Date(v),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}

export default function CoachDetail(){
 const {id}=useParams();const [coach,setCoach]=useState(null),[team,setTeam]=useState(null),[assignment,setAssignment]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!id)return;async function load(){try{const s=createSupabaseBrowserClient();const c=await s.from("coaches").select("id,full_name,date_of_birth,nationality,role,is_active,photo_url").eq("id",id).eq("is_active",true).maybeSingle();if(c.error)throw c.error;if(!c.data){setLoading(false);return}const tc=await s.from("team_coaches").select("role,start_date,team:teams!team_coaches_team_id_fkey(id,name,short_name,area,logo_url)").eq("coach_id",id).eq("is_current",true).maybeSingle();if(tc.error)throw tc.error;setCoach(c.data);setAssignment(tc.data||null);setTeam(tc.data?.team||null)}catch(e){setError(e?.message||"Coach data could not be loaded.")}finally{setLoading(false)}}load()},[id]);
 const age=ageFromDob(coach?.date_of_birth);
 if(loading)return <main><section className="container page-hero"><span className="section-kicker">Zedek Sports</span><h1>Coach</h1><p>Loading official coach profile…</p></section></main>;
 if(error||!coach)return <main><section className="container page-hero"><span className="section-kicker">Zedek Sports</span><h1>Coach not found</h1><p>{error||"This coach is not currently published."}</p><a className="button" href="/teams">← Back to teams</a></section></main>;
 return <main><section className="container player-profile-hero"><div className="player-profile-photo">{coach.photo_url?<img src={coach.photo_url} alt="" loading="eager" decoding="async" fetchPriority="high"/>:<span>{(coach.full_name||"C").slice(0,1)}</span>}</div><div className="player-profile-identity"><span className="section-kicker">{team?.area||"Oti local football"}</span><h1>{coach.full_name}</h1><p>{coach.role||"Coach"}{team?" • "+team.name:""}</p>{team&&<a href={"/teams/"+team.id} className="player-team-link">{team.short_name||team.name} → Squad</a>}</div></section><section className="container player-page"><div className="player-facts"><div><b>{age??"—"}</b><span>Age</span></div><div><b>{coach.role||"—"}</b><span>Role</span></div><div><b>{team?"Active":"—"}</b><span>Squad</span></div><div><b>{coach.nationality||"—"}</b><span>Nationality</span></div></div><div className="player-profile-grid"><section className="team-panel"><span className="section-kicker">COACH IDENTITY</span><h2>Profile</h2><div className="info-list">{age!=null&&<div><span>Age</span><b>{age} years</b></div>}{coach.date_of_birth&&<div><span>Date of birth</span><b>{date(coach.date_of_birth)}</b></div>}{coach.role&&<div><span>Role</span><b>{coach.role}</b></div>}{coach.nationality&&<div><span>Nationality</span><b>{coach.nationality}</b></div>}{team&&<div><span>Current club</span><b>{team.name}</b></div>}</div></section><section className="team-panel"><span className="section-kicker">SQUAD</span><h2>Current assignment</h2>{team?<div className="info-list"><div><span>Club</span><b>{team.name}</b></div><div><span>Area</span><b>{team.area||"—"}</b></div><div><span>Assignment</span><b>{assignment?.role||coach.role||"Coach"}</b></div><div><span>Since</span><b>{assignment?.start_date?date(assignment.start_date):"Current"}</b></div></div>:<div className="empty-state compact"><strong>No current squad assignment.</strong></div>}</section></div></section></main>
}