'use client';

import{useEffect,useState}from"react";
import{useParams}from"next/navigation";
import{createSupabaseBrowserClient}from"../../../lib/supabase/browser";

function date(v){return v?new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v)):"Date TBC"}
function TransferVisual({type,returning}){const tone=returning?"returning":type==="transfer"?"transfer":"loan";return <div className={"team-transfer-visual "+tone} aria-label={returning?"Returning loanee":type==="transfer"?"Transfer deal":"Loan deal"}><span className="team-transfer-curve" aria-hidden="true">↗</span><span className="team-transfer-handshake" aria-hidden="true">🤝</span></div>}

export default function TransferDetail(){
 const{id}=useParams();const[movement,setMovement]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!id)return;async function load(){try{const s=createSupabaseBrowserClient();const r=await s.from("player_movements").select("id,player_id,movement_type,start_date,end_date,status,notes,from_team_id,to_team_id,player:players(id,full_name,photo_url,shirt_number,position),from_team:teams!player_movements_from_team_id_fkey(id,name,short_name,logo_url,area),to_team:teams!player_movements_to_team_id_fkey(id,name,short_name,logo_url,area)").eq("id",id).maybeSingle();if(r.error)throw r.error;if(!r.data){setLoading(false);return}setMovement(r.data)}catch(e){setError(e?.message||"Transfer data could not be loaded")}finally{setLoading(false)}}load()},[id]);
 const returning=movement?.movement_type==="loan"&&/return|returning/i.test(movement?.notes||"");
 const label=returning?"Returning Loanee":movement?.movement_type==="transfer"?"Transfer":"Loan Deal";
 if(loading)return <main><section className="container page-hero"><span className="section-kicker">Zedek Sports</span><h1>Transfer</h1><p>Loading transfer details…</p></section></main>;
 if(error||!movement)return <main><section className="container page-hero"><span className="section-kicker">Zedek Sports</span><h1>Transfer not found</h1><p>{error||"This transfer record is not currently published."}</p><a className="button" href="/teams">← Back to teams</a></section></main>;
 return <main className="transfer-profile-page"><section className="container page-hero transfer-page-hero"><span className="section-kicker">TRANSFER HISTORY</span><h1>{label}</h1><p>Official player movement recorded by Zedek Sports.</p></section><section className="container transfer-detail-card"><div className="transfer-detail-top"><div><span className="section-kicker">{label}</span><strong>{date(movement.start_date)}</strong>{movement.end_date&&<small>Until {date(movement.end_date)}</small>}</div><span className="team-transfer-status">{movement.status}</span></div><div className="transfer-detail-inner"><div className="transfer-detail-team"><a href={"/teams/"+movement.from_team?.id} className="transfer-detail-team-link"><span className="team-transfer-logo">{movement.from_team?.logo_url?<img src={movement.from_team.logo_url} alt="" loading="eager" decoding="async"/>:<span>{(movement.from_team?.short_name||movement.from_team?.name||"F").slice(0,2).toUpperCase()}</span>}</span><strong>{movement.from_team?.name||"From team"}</strong><small>{movement.from_team?.area||""}</small></a></div><TransferVisual type={movement.movement_type} returning={returning}/><div className="transfer-detail-team"><a href={"/teams/"+movement.to_team?.id} className="transfer-detail-team-link"><span className="team-transfer-logo">{movement.to_team?.logo_url?<img src={movement.to_team.logo_url} alt="" loading="eager" decoding="async"/>:<span>{(movement.to_team?.short_name||movement.to_team?.name||"T").slice(0,2).toUpperCase()}</span>}</span><strong>{movement.to_team?.name||"To team"}</strong><small>{movement.to_team?.area||""}</small></a></div></div><div className="transfer-detail-player"><a href={"/players/"+movement.player?.id} className="transfer-detail-player-link">{movement.player?.photo_url?<img src={movement.player.photo_url} alt="" loading="eager" decoding="async"/>:<span>{(movement.player?.full_name||"P").slice(0,1)}</span>}<div><strong>{movement.player?.full_name||"Player"}</strong><small>{movement.player?.position||"Player"}{movement.player?.shirt_number!=null?" • #"+movement.player.shirt_number:""}</small></div></a></div><div className="transfer-detail-info"><div><span>Movement</span><b>{label}</b></div><div><span>Start date</span><b>{date(movement.start_date)}</b></div><div><span>End date</span><b>{movement.end_date?date(movement.end_date):"Not recorded"}</b></div><div><span>Status</span><b>{movement.status||"Not recorded"}</b></div></div>{movement.notes&&<div className="transfer-detail-notes"><span className="section-kicker">NOTES</span><p>{movement.notes}</p></div>}</section></main>
}
