'use client';

import {useState} from "react";
import {createSupabaseBrowserClient} from "../../lib/supabase/browser";

export default function FeedbackPage(){
 const [supabase]=useState(()=>createSupabaseBrowserClient());
 const [category,setCategory]=useState("general"),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[rating,setRating]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
 async function submit(e){e.preventDefault();setSaving(true);setError("");const {data:{session}}=await supabase.auth.getSession();if(!session){setSaving(false);setError("Please sign in before sending feedback.");return}const r=await supabase.from("user_feedback").insert({user_id:session.user.id,category,subject:subject.trim()||null,message:message.trim(),rating:rating?Number(rating):null});setSaving(false);if(r.error){setError(r.error.message);return}setDone(true);setSubject("");setMessage("");setRating("")}
 return <main><section className="container page-hero"><span className="section-kicker">ZEDEK SPORTS • Community</span><h1>Send feedback</h1><p>Report a problem, share a match note or tell us what you want Zedek Sports to improve.</p></section><section className="container" style={{maxWidth:820,paddingBottom:64}}>{done?<div className="panel"><h2>Thank you.</h2><p className="muted">Your feedback is now in the Zedek Sports review queue.</p><button className="button primary" onClick={()=>setDone(false)}>Send another</button></div>:<form className="panel form-stack" onSubmit={submit}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="general">General</option><option value="bug">Bug</option><option value="match">Match</option><option value="team">Team</option><option value="player">Player</option><option value="news">News</option><option value="feature">Feature request</option><option value="other">Other</option></select></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What is this about?"/></label><label>Message<textarea required minLength={5} rows="7" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell us what happened or what you would like to see…"/></label><label>Rating<select value={rating} onChange={e=>setRating(e.target.value)}><option value="">Optional</option><option value="1">1 — Very poor</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5 — Excellent</option></select></label>{error&&<div className="data-note"><strong>Could not send.</strong><span>{error}</span></div>}<button className="button primary" disabled={saving}>{saving?"Sending…":"Send feedback"}</button></form>}</section></main>
}